# Task to setup Jenkins


- name: Install Java {{ java_version }} OpenJDK Development Environment
  become: true
  yum:
    name: java-{{ java_version }}-openjdk-devel
    state: present


- name: Add Jenkins repository
  become: true
  yum_repository:
    name: jenkins
    description: Jenkins YUM repo
    file: /etc/yum.repos.d/jenkins
    baseurl: http://pkg.jenkins-ci.org/redhat-stable
    gpgcheck: yes


- name: Import rpm key
  become: true
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
    validate_certs: no


- name: Install Jenkins
  become: true
  yum:
    name: "jenkins-{{ jenkins_version }}"
    state: present
  notify:
    - stop jenkins
    - create jenkins user home directory and generate ssh key
    - create jenkins init scripts directory
    - setup jenkins environment
    - configure jenkin default users and security
    - restart jenkins
  register: jenkins_fresh_install


- name: Trigger handlers immediately
  meta: flush_handlers


- name: Remove Jenkins security init script
  become: true
  file:
    path: "{{ jenkins_home }}/init.groovy.d/basic_security.groovy"
    state: absent