- name: stop mysql
  become: true
  service:
    name: mysqld
    state: stopped


- name: change home directory in MySQL configuration file
  become: true
  lineinfile:
    dest: /etc/my.cnf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "^datadir=", line: "datadir={{ mysql_home }}" }
    - { regexp: "^socket=", line: "socket={{ mysql_home }}/mysql.sock" }


- name: add client properties in MySQL configuration file
  become: true
  lineinfile:
    dest: /etc/my.cnf
    line: "\n[client]\nport={{ mysql_client_port }}\nsocket={{ mysql_home }}/mysql.sock"
    state: present


- name: move mysql user home directory
  become: true
  user:
    name: mysql
    home: "{{ mysql_home }}"
    createhome: yes
    move_home: yes


- name: restart mysql
  become: true
  service:
    name: mysqld
    state: restarted
    enabled: yes
