# Tasks to set up firewall properties for a MySQL instance


- name: Create firewall rule for MySQL
  become: true
  command: "{{ item }}"
  with_items:
    - firewall-cmd --zone=public --add-port={{ mysql_client_port }}/tcp --permanent
    - firewall-cmd --reload
  when:
    - mysql_fresh_install.changed