# Tasks to perform a secure installation for MySQL (Oracle recommendations for MySQL prior 5.7)


- name: Disallow root login remotely
  command:
    mysql -u root -NBe \
    'DELETE FROM mysql.user WHERE User="root" AND Host NOT IN ("localhost", "127.0.0.1", "::1")'


- name: Get MySQL version.
  command: mysql --version
  register: mysql_cli_version
  changed_when: false


- name: Get list of hosts for the root user
  command:
    mysql -u root -NBe \
    'SELECT Host FROM mysql.user WHERE User = "root"'
  register: mysql_root_hosts


# Warning ! This is different for MySQL >= 5.7
- name: Update root password for localhost root account
  command:
    mysql -u root -NBe \
    'SET PASSWORD FOR "{{ mysql_root_account.user }}"@"{{ item }}" = PASSWORD("{{ mysql_root_account.password }}");'
  with_items: "{{ mysql_root_hosts.stdout_lines|default([]) }}"
  when:
    - mysql_cli_version.stdout.find('5.6.') != -1


- name: Remove anonymous users
  mysql_user:
    login_user: "{{ mysql_root_account.user }}"
    login_password: "{{ mysql_root_account.password }}"
    login_unix_socket: "{{ mysql_home }}/mysql.sock"
    name: ""
    host_all: yes
    state: absent


- name: Remove MySQL test database
  mysql_db:
    login_user: "{{ mysql_root_account.user }}"
    login_password: "{{ mysql_root_account.password }}"
    login_unix_socket: "{{ mysql_home }}/mysql.sock"
    name: test
    state: absent