# Main tasks


- include_vars: secrets.yml


- name: Check mandatory variables condition
  assert:
    that:
      - mariadb_version          is defined
      - mariadb_home             is defined
      - mariadb_port             is defined
      - mariadb_root_password    is defined
      - mariadb_app_database     is defined
      - mariadb_app_account      is defined
    msg: "Some variables are missing."


- include: "{{ deploy_tasks }}"
  with_items:
    - update_check.yml
    - firewall.yml
    - install.yml
    - secure_installation.yml
    - databases.yml
    - users.yml
  loop_control:
    loop_var: deploy_tasks


- name: Trigger handlers immediately
  meta: flush_handlers