# Task to install PHP for CentOS LAMP


- name: Install PHP {{ php_version }}
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php-{{ php_version }}
    - php-mysql-{{ php_version }}
  register: php_installation


- name: Restart Apache in order to work with PHP
  become: true
  service:
    name: httpd
    state: restarted
  when: php_installation.changed


# PHP / Apache works test -> <IP>/info.php
# Only for testing, keep it disable for server info protection
#- name: Create PHP info file
#  become: true
#  copy:
#    src: info.php
#    dest: /app/httpd/www/html/