# Task to install git on CentOS


- include_vars: secrets.yml


- name: Check mandatory variables condition
  assert:
    that:
      - git_version     is defined
      - git_home        is defined
      - git_env_path    is defined
    msg: "Some variables are missing."


- name: Uninstall previous
  become: true
  yum:
    name: git
    state: absent


- name: Install dependencies for Git compilation
  become: true
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - libcurl-devel
    - expat-devel
    - gettext
    - openssl-devel
    - perl-devel
    - zlib-devel


- name: Get Git {{ git_version }} sources
  become: true
  unarchive:
    src: https://github.com/git/git/archive/v{{ git_version }}.tar.gz
    dest: /opt/
    remote_src: yes
  changed_when: false


- name: Compile Git {{ git_version }} sources
  become: true
  shell: |
    make prefix={{ git_home }} all
    make prefix={{ git_home }} install
  args:
    chdir: /opt/git-{{ git_version }}/
    creates: "{{ git_home }}"


- name: Setup environment with Git {{ git_version }}
  become: true
  template:
    src: git.sh
    dest: /etc/profile.d/git.sh