- name: restart sshd
  become: true
  service:
    name: sshd
    state: restarted


- name: reboot machine
  become: true
  shell:
    sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  changed_when: true
  notify:
    - waiting for server to come back


- name: waiting for server to come back
  local_action: wait_for
    host={{ ansible_host }}
    port={{ ansible_port }}
    delay=20
    timeout=120