# Tasks for app directory and users creations


- name: Create app directory
  become: true
  file:
    path: /app
    state: directory


# ---------------------------------------------------------------------------------


- name: Create admin users
  become: true
  user:
    name: "{{ item.user }}"
  with_items: "{{ admin_users }}"


- name: Add admins to sudoers
  become: true
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item.user }} ALL\='
    line: '{{ item.user }} ALL=(ALL) NOPASSWD:ALL'
    state: present
    validate: 'visudo -cf %s'
  with_items: "{{ admin_users }}"


- name: Add admin_users ssh keys in authorized_keys
  become: true
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
  with_items: "{{ admin_users }}"