# Main task


- include_vars: secrets.yml


- name: Check mandatory variables condition
  assert:
    that:
      - admin_users         is defined
    msg: "Some variables are missing."


- include: "{{ deploy_tasks }}"
  with_items:
    - packages.yml
    - hostname.yml
    - app_and_users.yml
    - security.yml
  loop_control:
    loop_var: deploy_tasks


- name: Trigger handlers immediately
  meta: flush_handlers